/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Core dependencies
    implementation(libs.guava)
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.0.21")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Configure multiple main classes
tasks.register<JavaExec>("runHelloWorld") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.example1.HelloWorldKt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runBasicCoroutines") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.example4.BasicCoroutinesKt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runCoroutineApp2") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.example2.CoroutineApp2Kt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runCoroutineApp3") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.example3.AppKt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runCoroutineApp41") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.example4.example41.AppKt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runCoroutineApp5") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.example5.AppKt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runUsingCoroutinesExample1") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.using_coroutines.Example1Kt"
    classpath = sourceSets["main"].runtimeClasspath
}

tasks.register<JavaExec>("runUsingCoroutinesExample2") {
    group = "application"
    mainClass = "com.vuanhshow.coroutines.examples.using_coroutines.Example2Kt"
    classpath = sourceSets["main"].runtimeClasspath
}

// Default application configuration
application {
    mainClass = "com.vuanhshow.coroutines.examples.example1.HelloWorldKt"
}
